name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Update Build Date
        run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" Archivist.lua

      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}

      - uses: actions/upload-artifact@v1.0.0
        with:
          name: Archivist-CI
          path: .release/Archivist

      - name: Notify on Failure
        if: failure()
        env:
          BUILD_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: curl -s https://raw.githubusercontent.com/nebularg/actions-discord-webhook/master/send.sh | bash
